import { FishProduct, KitchenMenuItem, Store, Order, CuttingType } from './types';

// Common cutting types
export const defaultCuttingTypes: CuttingType[] = [
  { id: 'ct-1', name: 'Whole Fish', image: '🐟', description: 'Complete fish, cleaned and scaled' },
  { id: 'ct-2', name: 'Fillet', image: '🔪', description: 'Boneless fillet cuts' },
  { id: 'ct-3', name: 'Steaks', image: '🥩', description: 'Cross-cut steaks with bone' },
  { id: 'ct-4', name: 'Cubes', image: '🧊', description: 'Bite-sized cubes for curry' },
  { id: 'ct-5', name: 'Cleaned Only', image: '✨', description: 'Cleaned, gutted, scales removed' },
];

export const shrimpCuttingTypes: CuttingType[] = [
  { id: 'ct-6', name: 'Shell On', image: '🦐', description: 'With shell, deveined' },
  { id: 'ct-7', name: 'Peeled', image: '🍤', description: 'Shell removed, deveined' },
  { id: 'ct-8', name: 'Butterfly', image: '🦋', description: 'Split and flattened' },
];

export const squidCuttingTypes: CuttingType[] = [
  { id: 'ct-9', name: 'Rings', image: '⭕', description: 'Classic calamari rings' },
  { id: 'ct-10', name: 'Strips', image: '📏', description: 'Long strips for stir-fry' },
  { id: 'ct-11', name: 'Whole Cleaned', image: '✨', description: 'Whole tube, cleaned' },
];

export const mockCatchOfTheDay: FishProduct[] = [
  {
    id: 'cod-1',
    name: 'Atlantic Cod',
    description: 'Wild-caught Atlantic cod, firm white flesh perfect for grilling or frying. Caught fresh this morning.',
    category: 'White Fish',
    image: '',
    pricePerKg: 850,
    weightOptions: [500, 1000, 2000],
    stock: 12,
    isCatchOfTheDay: true,
    isPreOrder: false,
    freshnessTags: ["Today's Fresh Catch", 'Wild Caught'],
    origin: 'North Atlantic',
    isUrbanFish: true,
    cuttingTypes: defaultCuttingTypes,
  },
  {
    id: 'prawn-1',
    name: 'Tiger Prawns',
    description: 'Jumbo tiger prawns, deveined and cleaned. Farm-raised with sustainable practices.',
    category: 'Shellfish',
    image: '',
    pricePerKg: 1200,
    weightOptions: [250, 500, 1000],
    stock: 8,
    isCatchOfTheDay: true,
    isPreOrder: false,
    freshnessTags: ["Today's Fresh Catch", 'Sustainable'],
    origin: 'Coastal Farm',
    isUrbanFish: true,
    cuttingTypes: shrimpCuttingTypes,
  },
  {
    id: 'salmon-1',
    name: 'Norwegian Salmon',
    description: 'Premium Norwegian salmon fillet. Rich in Omega-3, perfect for sashimi or baking.',
    category: 'Fatty Fish',
    image: '',
    pricePerKg: 1800,
    weightOptions: [250, 500, 1000],
    stock: 5,
    isCatchOfTheDay: true,
    isPreOrder: false,
    freshnessTags: ["Today's Fresh Catch", 'Premium'],
    origin: 'Norway',
    isUrbanFish: true,
    cuttingTypes: defaultCuttingTypes,
  },
];

export const mockPreOrderFish: FishProduct[] = [
  {
    id: 'hilsa-1',
    name: 'Hilsa Fish',
    description: 'The king of fish! Premium Hilsa with rich flavor. Pre-order to get the freshest catch delivered tomorrow.',
    category: 'Fatty Fish',
    image: '',
    pricePerKg: 1600,
    weightOptions: [500, 1000, 2000],
    stock: 999,
    isCatchOfTheDay: false,
    isPreOrder: true,
    freshnessTags: ['Pre-Order'],
    origin: 'Bay of Bengal',
    isUrbanFish: true,
    cuttingTypes: defaultCuttingTypes,
  },
  {
    id: 'surmai-1',
    name: 'Surmai (Indo-Pacific King Mackerel)',
    description: 'Firm, flavorful Surmai steaks. Pre-order now for tomorrow\'s fresh delivery.',
    category: 'Fatty Fish',
    image: '',
    pricePerKg: 1300,
    weightOptions: [500, 1000, 2000],
    stock: 999,
    isCatchOfTheDay: false,
    isPreOrder: true,
    freshnessTags: ['Pre-Order'],
    origin: 'Indian Ocean',
    isUrbanFish: true,
    cuttingTypes: defaultCuttingTypes,
  },
  {
    id: 'rohu-1',
    name: 'Rohu Fish',
    description: 'Fresh water Rohu, perfect for Bengali-style curry. Pre-order for guaranteed freshness.',
    category: 'Freshwater Fish',
    image: '',
    pricePerKg: 350,
    weightOptions: [500, 1000, 2000, 5000],
    stock: 999,
    isCatchOfTheDay: false,
    isPreOrder: true,
    freshnessTags: ['Pre-Order'],
    origin: 'River Farms',
    isUrbanFish: true,
    cuttingTypes: defaultCuttingTypes,
  },
  {
    id: 'catla-1',
    name: 'Catla Fish',
    description: 'Premium Catla, great for frying and curries. Fresh procurement based on your order.',
    category: 'Freshwater Fish',
    image: '',
    pricePerKg: 300,
    weightOptions: [500, 1000, 2000],
    stock: 999,
    isCatchOfTheDay: false,
    isPreOrder: true,
    freshnessTags: ['Pre-Order'],
    origin: 'River Farms',
    isUrbanFish: true,
    cuttingTypes: defaultCuttingTypes,
  },
];

export const mockUrbanFishProducts: FishProduct[] = [
  ...mockCatchOfTheDay,
  ...mockPreOrderFish,
  {
    id: 'pomfret-1',
    name: 'Silver Pomfret',
    description: 'Fresh silver pomfret, ideal for steaming or frying. Delicate flavor and tender meat.',
    category: 'White Fish',
    image: '',
    pricePerKg: 950,
    weightOptions: [500, 1000],
    stock: 20,
    isCatchOfTheDay: false,
    isPreOrder: false,
    freshnessTags: ['Wild Caught'],
    origin: 'Arabian Sea',
    isUrbanFish: true,
    cuttingTypes: defaultCuttingTypes,
  },
  {
    id: 'seer-1',
    name: 'King Fish (Seer)',
    description: 'Premium seer fish steaks, firm texture with rich taste. Perfect for curry or tandoori.',
    category: 'Fatty Fish',
    image: '',
    pricePerKg: 1100,
    weightOptions: [500, 1000, 2000],
    stock: 15,
    isCatchOfTheDay: false,
    isPreOrder: false,
    freshnessTags: ['Fresh'],
    origin: 'Indian Ocean',
    isUrbanFish: true,
    cuttingTypes: defaultCuttingTypes,
  },
  {
    id: 'squid-1',
    name: 'Fresh Squid',
    description: 'Cleaned and ready-to-cook squid rings. Tender and versatile.',
    category: 'Cephalopod',
    image: '',
    pricePerKg: 650,
    weightOptions: [250, 500, 1000],
    stock: 25,
    isCatchOfTheDay: false,
    isPreOrder: false,
    freshnessTags: ['Cleaned'],
    origin: 'Coastal Waters',
    isUrbanFish: true,
    cuttingTypes: squidCuttingTypes,
  },
];

export const mockKitchenMenu: KitchenMenuItem[] = [
  {
    id: 'km-1',
    name: 'Grilled Salmon Bowl',
    description: 'Herb-crusted grilled salmon on a bed of quinoa with roasted vegetables and lemon dill sauce.',
    image: '',
    price: 450,
    category: 'Bowls',
    isAvailable: true,
    preparationTime: 25,
    calories: 520,
    tags: ['High Protein', 'Omega-3 Rich'],
  },
  {
    id: 'km-2',
    name: 'Prawn Stir-Fry',
    description: 'Wok-tossed prawns with fresh vegetables in a light ginger-garlic sauce. Served with steamed rice.',
    image: '',
    price: 380,
    category: 'Mains',
    isAvailable: true,
    preparationTime: 20,
    calories: 420,
    tags: ['Low Calorie', 'Gluten Free'],
  },
  {
    id: 'km-3',
    name: 'Fish Tacos',
    description: 'Crispy battered fish with pickled cabbage slaw, chipotle mayo in soft corn tortillas.',
    image: '',
    price: 320,
    category: 'Quick Bites',
    isAvailable: true,
    preparationTime: 15,
    calories: 380,
    tags: ['Quick Prep'],
  },
  {
    id: 'km-4',
    name: 'Seafood Chowder',
    description: 'Creamy New England-style chowder loaded with shrimp, clams, and fresh fish chunks.',
    image: '',
    price: 280,
    category: 'Soups',
    isAvailable: true,
    preparationTime: 30,
    calories: 350,
    tags: ['Comfort Food', 'Warming'],
  },
];

export const mockStores: Store[] = [
  {
    id: 'store-1',
    sellerId: 'seller-1',
    name: 'Marina Fresh Fish',
    description: 'Family-owned fish market operating since 1985. We source directly from local fishermen every morning.',
    logo: '',
    rating: 4.6,
    reviewCount: 234,
    deliveryRadius: 10,
    operatingHours: '6:00 AM - 8:00 PM',
    isApproved: true,
    isActive: true,
  },
  {
    id: 'store-2',
    sellerId: 'seller-2',
    name: 'Ocean Harvest',
    description: 'Specializing in premium imported seafood. From Norwegian salmon to Japanese tuna.',
    logo: '',
    rating: 4.8,
    reviewCount: 156,
    deliveryRadius: 15,
    operatingHours: '7:00 AM - 9:00 PM',
    isApproved: true,
    isActive: true,
  },
  {
    id: 'store-3',
    sellerId: 'seller-3',
    name: 'Coastal Catch',
    description: 'Sustainable seafood from responsible fisheries. Every purchase supports ocean conservation.',
    logo: '',
    rating: 4.4,
    reviewCount: 89,
    deliveryRadius: 8,
    operatingHours: '5:30 AM - 7:00 PM',
    isApproved: true,
    isActive: true,
  },
];

export const mockStoreProducts: Record<string, FishProduct[]> = {
  'store-1': [
    {
      id: 'sp-1',
      storeId: 'store-1',
      name: 'Red Snapper',
      description: 'Freshly caught red snapper, whole or filleted.',
      category: 'White Fish',
      image: '',
      pricePerKg: 780,
      weightOptions: [500, 1000],
      stock: 10,
      isCatchOfTheDay: true,
      isPreOrder: false,
      freshnessTags: ["Today's Fresh Catch"],
      isUrbanFish: false,
      cuttingTypes: defaultCuttingTypes,
    },
    {
      id: 'sp-2',
      storeId: 'store-1',
      name: 'Mud Crab',
      description: 'Live mud crabs, heavy and meaty.',
      category: 'Shellfish',
      image: '',
      pricePerKg: 1400,
      weightOptions: [500, 1000],
      stock: 6,
      isCatchOfTheDay: false,
      isPreOrder: false,
      freshnessTags: ['Live'],
      isUrbanFish: false,
    },
  ],
  'store-2': [
    {
      id: 'sp-3',
      storeId: 'store-2',
      name: 'Bluefin Tuna',
      description: 'Sashimi-grade bluefin tuna, imported weekly.',
      category: 'Fatty Fish',
      image: '',
      pricePerKg: 3200,
      weightOptions: [250, 500],
      stock: 3,
      isCatchOfTheDay: false,
      isPreOrder: false,
      freshnessTags: ['Premium', 'Sashimi Grade'],
      isUrbanFish: false,
      cuttingTypes: defaultCuttingTypes,
    },
  ],
  'store-3': [
    {
      id: 'sp-4',
      storeId: 'store-3',
      name: 'Mackerel',
      description: 'Sustainably caught Indian mackerel.',
      category: 'Fatty Fish',
      image: '',
      pricePerKg: 350,
      weightOptions: [500, 1000, 2000],
      stock: 40,
      isCatchOfTheDay: false,
      isPreOrder: false,
      freshnessTags: ['Sustainable', 'Wild Caught'],
      isUrbanFish: false,
      cuttingTypes: defaultCuttingTypes,
    },
  ],
};

// Mock orders for admin dashboard
export const mockOrders: Order[] = [
  {
    id: 'ORD-1001',
    userId: 'user-1',
    customerName: 'Rahul Sharma',
    customerEmail: 'rahul@example.com',
    items: [
      { product: mockCatchOfTheDay[0], quantity: 2, weight: 1000 },
      { product: mockKitchenMenu[0], quantity: 1 },
    ],
    total: 2150,
    status: 'order_received',
    deliveryAddress: {
      id: 'addr-1', userId: 'user-1', label: 'Home', fullName: 'Rahul Sharma',
      line1: '12, MG Road', city: 'Mumbai', state: 'Maharashtra', pincode: '400001', phone: '9876543210', isDefault: true,
    },
    createdAt: new Date().toISOString(),
    paymentStatus: 'paid',
  },
  {
    id: 'ORD-1002',
    userId: 'user-2',
    customerName: 'Priya Nair',
    customerEmail: 'priya@example.com',
    items: [
      { product: mockCatchOfTheDay[1], quantity: 1, weight: 500 },
    ],
    total: 600,
    status: 'preparing',
    deliveryAddress: {
      id: 'addr-2', userId: 'user-2', label: 'Office', fullName: 'Priya Nair',
      line1: '45, Linking Road', city: 'Mumbai', state: 'Maharashtra', pincode: '400050', phone: '9123456789', isDefault: true,
    },
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    paymentStatus: 'paid',
  },
  {
    id: 'ORD-1003',
    userId: 'user-3',
    customerName: 'Arun Kumar',
    customerEmail: 'arun@example.com',
    items: [
      { product: mockKitchenMenu[1], quantity: 2 },
      { product: mockKitchenMenu[3], quantity: 1 },
    ],
    total: 1040,
    status: 'out_for_delivery',
    deliveryAddress: {
      id: 'addr-3', userId: 'user-3', label: 'Home', fullName: 'Arun Kumar',
      line1: '78, Anna Salai', city: 'Chennai', state: 'Tamil Nadu', pincode: '600002', phone: '9988776655', isDefault: true,
    },
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    paymentStatus: 'paid',
  },
  {
    id: 'ORD-1004',
    userId: 'user-4',
    customerName: 'Sneha Patel',
    customerEmail: 'sneha@example.com',
    items: [
      { product: mockUrbanFishProducts.find(f => f.id === 'pomfret-1')!, quantity: 1, weight: 1000 },
    ],
    total: 950,
    status: 'delivered',
    deliveryAddress: {
      id: 'addr-4', userId: 'user-4', label: 'Home', fullName: 'Sneha Patel',
      line1: '23, SG Highway', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015', phone: '9876501234', isDefault: true,
    },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    paymentStatus: 'paid',
  },
  {
    id: 'ORD-1005',
    userId: 'user-5',
    customerName: 'Deepak Reddy',
    customerEmail: 'deepak@example.com',
    items: [
      { product: mockUrbanFishProducts.find(f => f.id === 'seer-1')!, quantity: 1, weight: 2000 },
      { product: mockKitchenMenu[2], quantity: 3 },
    ],
    total: 3160,
    status: 'delivered',
    deliveryAddress: {
      id: 'addr-5', userId: 'user-5', label: 'Home', fullName: 'Deepak Reddy',
      line1: '56, Jubilee Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500033', phone: '9012345678', isDefault: true,
    },
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    paymentStatus: 'paid',
  },
];
