import { FishProduct, KitchenMenuItem, Store } from './types';

export const mockCatchOfTheDay: FishProduct[] = [
  {
    id: 'cod-1',
    name: 'Atlantic Cod',
    description: 'Wild-caught Atlantic cod, firm white flesh perfect for grilling or frying. Caught fresh this morning.',
    category: 'White Fish',
    image: '',
    pricePerKg: 850,
    weightOptions: [500, 1000, 2000],
    stock: 12,
    isCatchOfTheDay: true,
    freshnessTags: ["Today's Fresh Catch", 'Wild Caught'],
    origin: 'North Atlantic',
    isUrbanFish: true,
  },
  {
    id: 'prawn-1',
    name: 'Tiger Prawns',
    description: 'Jumbo tiger prawns, deveined and cleaned. Farm-raised with sustainable practices.',
    category: 'Shellfish',
    image: '',
    pricePerKg: 1200,
    weightOptions: [250, 500, 1000],
    stock: 8,
    isCatchOfTheDay: true,
    freshnessTags: ["Today's Fresh Catch", 'Sustainable'],
    origin: 'Coastal Farm',
    isUrbanFish: true,
  },
  {
    id: 'salmon-1',
    name: 'Norwegian Salmon',
    description: 'Premium Norwegian salmon fillet. Rich in Omega-3, perfect for sashimi or baking.',
    category: 'Fatty Fish',
    image: '',
    pricePerKg: 1800,
    weightOptions: [250, 500, 1000],
    stock: 5,
    isCatchOfTheDay: true,
    freshnessTags: ["Today's Fresh Catch", 'Premium'],
    origin: 'Norway',
    isUrbanFish: true,
  },
];

export const mockUrbanFishProducts: FishProduct[] = [
  ...mockCatchOfTheDay,
  {
    id: 'pomfret-1',
    name: 'Silver Pomfret',
    description: 'Fresh silver pomfret, ideal for steaming or frying. Delicate flavor and tender meat.',
    category: 'White Fish',
    image: '',
    pricePerKg: 950,
    weightOptions: [500, 1000],
    stock: 20,
    isCatchOfTheDay: false,
    freshnessTags: ['Wild Caught'],
    origin: 'Arabian Sea',
    isUrbanFish: true,
  },
  {
    id: 'seer-1',
    name: 'King Fish (Seer)',
    description: 'Premium seer fish steaks, firm texture with rich taste. Perfect for curry or tandoori.',
    category: 'Fatty Fish',
    image: '',
    pricePerKg: 1100,
    weightOptions: [500, 1000, 2000],
    stock: 15,
    isCatchOfTheDay: false,
    freshnessTags: ['Fresh'],
    origin: 'Indian Ocean',
    isUrbanFish: true,
  },
  {
    id: 'squid-1',
    name: 'Fresh Squid',
    description: 'Cleaned and ready-to-cook squid rings. Tender and versatile.',
    category: 'Cephalopod',
    image: '',
    pricePerKg: 650,
    weightOptions: [250, 500, 1000],
    stock: 25,
    isCatchOfTheDay: false,
    freshnessTags: ['Cleaned'],
    origin: 'Coastal Waters',
    isUrbanFish: true,
  },
];

export const mockKitchenMenu: KitchenMenuItem[] = [
  {
    id: 'km-1',
    name: 'Grilled Salmon Bowl',
    description: 'Herb-crusted grilled salmon on a bed of quinoa with roasted vegetables and lemon dill sauce.',
    image: '',
    price: 450,
    category: 'Bowls',
    isAvailable: true,
    preparationTime: 25,
    calories: 520,
    tags: ['High Protein', 'Omega-3 Rich'],
  },
  {
    id: 'km-2',
    name: 'Prawn Stir-Fry',
    description: 'Wok-tossed prawns with fresh vegetables in a light ginger-garlic sauce. Served with steamed rice.',
    image: '',
    price: 380,
    category: 'Mains',
    isAvailable: true,
    preparationTime: 20,
    calories: 420,
    tags: ['Low Calorie', 'Gluten Free'],
  },
  {
    id: 'km-3',
    name: 'Fish Tacos',
    description: 'Crispy battered fish with pickled cabbage slaw, chipotle mayo in soft corn tortillas.',
    image: '',
    price: 320,
    category: 'Quick Bites',
    isAvailable: true,
    preparationTime: 15,
    calories: 380,
    tags: ['Quick Prep'],
  },
  {
    id: 'km-4',
    name: 'Seafood Chowder',
    description: 'Creamy New England-style chowder loaded with shrimp, clams, and fresh fish chunks.',
    image: '',
    price: 280,
    category: 'Soups',
    isAvailable: true,
    preparationTime: 30,
    calories: 350,
    tags: ['Comfort Food', 'Warming'],
  },
];

export const mockStores: Store[] = [
  {
    id: 'store-1',
    sellerId: 'seller-1',
    name: 'Marina Fresh Fish',
    description: 'Family-owned fish market operating since 1985. We source directly from local fishermen every morning.',
    logo: '',
    rating: 4.6,
    reviewCount: 234,
    deliveryRadius: 10,
    operatingHours: '6:00 AM - 8:00 PM',
    isApproved: true,
    isActive: true,
  },
  {
    id: 'store-2',
    sellerId: 'seller-2',
    name: 'Ocean Harvest',
    description: 'Specializing in premium imported seafood. From Norwegian salmon to Japanese tuna.',
    logo: '',
    rating: 4.8,
    reviewCount: 156,
    deliveryRadius: 15,
    operatingHours: '7:00 AM - 9:00 PM',
    isApproved: true,
    isActive: true,
  },
  {
    id: 'store-3',
    sellerId: 'seller-3',
    name: 'Coastal Catch',
    description: 'Sustainable seafood from responsible fisheries. Every purchase supports ocean conservation.',
    logo: '',
    rating: 4.4,
    reviewCount: 89,
    deliveryRadius: 8,
    operatingHours: '5:30 AM - 7:00 PM',
    isApproved: true,
    isActive: true,
  },
];

export const mockStoreProducts: Record<string, FishProduct[]> = {
  'store-1': [
    {
      id: 'sp-1',
      storeId: 'store-1',
      name: 'Red Snapper',
      description: 'Freshly caught red snapper, whole or filleted.',
      category: 'White Fish',
      image: '',
      pricePerKg: 780,
      weightOptions: [500, 1000],
      stock: 10,
      isCatchOfTheDay: true,
      freshnessTags: ["Today's Fresh Catch"],
      isUrbanFish: false,
    },
    {
      id: 'sp-2',
      storeId: 'store-1',
      name: 'Mud Crab',
      description: 'Live mud crabs, heavy and meaty.',
      category: 'Shellfish',
      image: '',
      pricePerKg: 1400,
      weightOptions: [500, 1000],
      stock: 6,
      isCatchOfTheDay: false,
      freshnessTags: ['Live'],
      isUrbanFish: false,
    },
  ],
  'store-2': [
    {
      id: 'sp-3',
      storeId: 'store-2',
      name: 'Bluefin Tuna',
      description: 'Sashimi-grade bluefin tuna, imported weekly.',
      category: 'Fatty Fish',
      image: '',
      pricePerKg: 3200,
      weightOptions: [250, 500],
      stock: 3,
      isCatchOfTheDay: false,
      freshnessTags: ['Premium', 'Sashimi Grade'],
      isUrbanFish: false,
    },
  ],
  'store-3': [
    {
      id: 'sp-4',
      storeId: 'store-3',
      name: 'Mackerel',
      description: 'Sustainably caught Indian mackerel.',
      category: 'Fatty Fish',
      image: '',
      pricePerKg: 350,
      weightOptions: [500, 1000, 2000],
      stock: 40,
      isCatchOfTheDay: false,
      freshnessTags: ['Sustainable', 'Wild Caught'],
      isUrbanFish: false,
    },
  ],
};
